{"status":"OK","subtests":[{"name":"Return NotSupportedError when calling observer()","status":"FAIL"},{"name":"Basic functionality test","status":"FAIL"},{"name":"Removing observer before observe() resolves works","status":"FAIL"},{"name":"Calling observe() multiple times works","status":"FAIL"},{"name":"Starting a new observer after an observer has started works","status":"FAIL"}]}