{"status":"OK","subtests":[{"name":"global setup","status":"PASS"},{"name":"FetchEvent.handled should resolve when respondWith() is not called for a navigation request","status":"PASS"},{"name":"FetchEvent.handled should resolve when respondWith() is not called for a sub-resource request","status":"PASS"},{"name":"FetchEvent.handled should reject when respondWith() is not called and the event is canceled","status":"PASS"},{"name":"FetchEvent.handled should resolve when the promise provided to respondWith() is resolved","status":"PASS"},{"name":"FetchEvent.handled should reject when the promise provided to respondWith() is resolved to an invalid response","status":"PASS"},{"name":"FetchEvent.handled should reject when the promise provided to respondWith() is rejected","status":"PASS"},{"name":"global cleanup","status":"PASS"}]}