{"status":"OK","subtests":[{"name":"Test pausing then playing does not change the finished promise","status":"FAIL"},{"name":"Test restarting a finished animation","status":"FAIL"},{"name":"Test restarting a reversed finished animation","status":"FAIL"},{"name":"Test redundant finishing of animation","status":"FAIL"},{"name":"Finished promise does not resolve when paused","status":"FAIL"},{"name":"Finished promise does not resolve when pause-pending","status":"FAIL"},{"name":"The finished promise is fulfilled with its Animation","status":"FAIL"},{"name":"finished promise is rejected when an animation is canceled by calling cancel()","status":"FAIL"},{"name":"canceling an already-finished animation replaces the finished promise","status":"FAIL"},{"name":"Test finished promise changes for animation duration changes","status":"FAIL"},{"name":"Test finished promise changes when playbackRate == 0","status":"FAIL"},{"name":"Test finished promise resolves when reaching to the natural boundary.","status":"FAIL"},{"name":"Test finished promise changes when a prior finished promise resolved and the animation falls out finished state","status":"FAIL"},{"name":"Test no new finished promise generated when finished state is checked asynchronously","status":"FAIL"},{"name":"Test new finished promise generated when finished state is checked synchronously","status":"FAIL"},{"name":"Test synchronous finished promise resolved even if finished state is changed soon","status":"FAIL"},{"name":"Test synchronous finished promise resolved even if asynchronous finished promise happens just before synchronous promise","status":"FAIL"},{"name":"Test finished promise is not resolved when the animation falls out finished state immediately","status":"FAIL"},{"name":"Test finished promise is not resolved once the animation falls out finished state even though the current finished promise is generated soon after animation state became finished","status":"FAIL"},{"name":"Finished promise should be resolved after the ready promise is resolved","status":"FAIL"},{"name":"Finished promise should be rejected after the ready promise is rejected","status":"FAIL"}]}