{"status":"TIMEOUT","subtests":[{"name":"# AUDIT TASK RUNNER STARTED.","status":"PASS"},{"name":"Executing \"test-suspend\"","status":"PASS"},{"name":"Executing \"test-resume\"","status":"PASS"},{"name":"Executing \"test-after-close\"","status":"PASS"},{"name":"Executing \"resume-running-context\"","status":"TIMEOUT"},{"name":"Audit report","status":"NOTRUN"},{"name":"> [test-suspend] Test suspend() for offline context","status":"PASS"},{"name":"  offlineContext = new OfflineAudioContext(1, 44100, 44100) did not throw an exception.","status":"PASS"},{"name":"  offlineContext.state is equal to suspended.","status":"PASS"},{"name":"  p1 = offlineContext.suspend() did not throw an exception.","status":"PASS"},{"name":"  p1 instanceof Promise is true.","status":"PASS"},{"name":"  p1 rejected correctly with TypeError: Not enough arguments.","status":"PASS"},{"name":"< [test-suspend] All assertions passed. (total 5 assertions)","status":"PASS"},{"name":"> [test-resume] Test resume() for offline context","status":"PASS"},{"name":"  p2 = offlineContext.resume() did not throw an exception.","status":"PASS"},{"name":"  p2 instanceof Promise is true.","status":"PASS"},{"name":"  After resume, offlineContext.state is equal to suspended.","status":"PASS"},{"name":"  p2 rejected correctly with InvalidStateError: Cannot resume an offline audio context that has not started.","status":"PASS"},{"name":"< [test-resume] All assertions passed. (total 4 assertions)","status":"PASS"},{"name":"> [test-after-close] Test state after context closed","status":"PASS"},{"name":"  p3 = offlineContext.startRendering() did not throw an exception.","status":"PASS"},{"name":"  After close, offlineContext.state is equal to closed.","status":"PASS"},{"name":"  offlineContext.suspend() rejected correctly with TypeError: Not enough arguments.","status":"PASS"},{"name":"  offlineContext.resume() rejected correctly with InvalidStateError: Cannot resume an offline audio context that has not started.","status":"PASS"},{"name":"< [test-after-close] All assertions passed. (total 4 assertions)","status":"PASS"},{"name":"> [resume-running-context] Test resuming a running context","status":"PASS"},{"name":"  Create online context did not throw an exception.","status":"PASS"},{"name":"  context.state is equal to suspended.","status":"PASS"}]}