{"status":"OK","subtests":[{"name":"Calling remote.prompt() in a detached context should throw InvalidAccessError","status":"PASS"}]}