{"status":"ERROR","subtests":[{"name":"navigate() and intercept() with a rejected promise","status":"FAIL"}]}