{"status":"ERROR","subtests":[{"name":"User allows access, check that success callback is called.","status":"FAIL"}]}