{"status":"OK","subtests":[{"name":"Call watchPosition without arguments, check that exception is thrown","status":"PASS"},{"name":"Call watchPosition with null success callback, check that exception is thrown","status":"PASS"},{"name":"Call watchPosition with null success and error callbacks, check that exception is thrown","status":"PASS"},{"name":"Call watchPosition() with wrong type for first argument. Exception expected.","status":"PASS"},{"name":"Call watchPosition() with wrong type for second argument. Exception expected.","status":"PASS"},{"name":"Call watchPosition() with wrong type for third argument. Exception expected.","status":"PASS"}]}