{"status":"OK","subtests":[{"name":"Explicitly committed data can be read back out.","status":"PASS"},{"name":"commit() on a version change transaction does not cause errors.","status":"PASS"},{"name":"A committed transaction becomes inactive immediately.","status":"PASS"},{"name":"A committed transaction is inactive in future request callbacks.","status":"PASS"},{"name":"Puts issued after commit are not fulfilled.","status":"PASS"},{"name":"Calling commit on an aborted transaction throws.","status":"PASS"},{"name":"Calling commit on a committed transaction throws.","status":"PASS"},{"name":"Calling abort on a committed transaction throws and does not prevent persisting the data.","status":"PASS"},{"name":"Calling txn.commit() when txn is inactive should throw.","status":"PASS"},{"name":"Transactions with same scope should stay in program order, even if one calls commit.","status":"PASS"},{"name":"Transactions that explicitly commit and have errors should abort.","status":"PASS"},{"name":"Transactions that handle all errors properly should behave as expected when an explicit commit is called in an onerror handler.","status":"PASS"}]}