{"status":"OK","subtests":[{"name":"disconnect() and connect() called during getCharacteristics. Reject with NetworkError.","status":"FAIL"}]}