{"status":"OK","subtests":[{"name":"Successful attachInternals() and the second call.","status":"FAIL"},{"name":"attachInternals() throws a NotSupportedError if it is called for a customized built-in element","status":"FAIL"},{"name":"If a custom element definition for the local name of the element doesn't exist, throw an NotSupportedError","status":"FAIL"},{"name":"If a custom element definition for the local name of the element has disable internals flag, throw a NotSupportedError","status":"FAIL"}]}